### ISSUE TITLE
Criar mundo para o Gazebo

### ISSUE THREAD

**Issue by emersonfs** [laserjames/james-manipulator#4]
Precisamos de um mundo no Gazebo onde existam objetos para o manipulador fazer as tarefas de *pick and place*, com, por exemplo, uma mesa e uma garrafa de cerveja, coisas assim.

Tutoriais sobre como fazer isso podem ser achados [aqui](http://gazebosim.org/tutorials/?cat=build_world). Exemplos podem ser achados [aqui](https://github.com/AaronMR/Learning_ROS_for_Robotics_Programming_2nd_edition/tree/hydro-devel/chapter10_tutorials/rosbook_arm_gazebo/worlds).

Lembrando que a versão do Gazebo usada é a 2.2.6, portanto o negócio é seguir os tutoriais para versões < 2.2.

**Comment by Kenedw** [comment]
estou com um errinho aqui que deve ser coisa simples, mas to me enrolando todo, da uma olhada pfv nesses dois arquivos, deixei bem simples, só pra analisar o erro mesmo.


Kened Wanderson Cruz OliveiraUndergrad Student - Computer Engineering at UFPBE-mail: kened.wanderson@eng.ci.ufpb.br / kenedwanderson@live.com

Date: Tue, 26 Jan 2016 08:17:47 -0800

**Comment by Kenedw** [comment]
https://gist.github.com/Kenedw/e95b5596ebbc3c770966


olha se ficou legal esse world, são duas mesas com alguns objetos sortidos nela, o objetivo seria pegar um objeto e colocar na outra mesa

**Comment by emersonfs** [comment]
Ótimo trabalho, @Kenedw!

Pode colocar os arquivos no repositório, mas, antes, podes diminuir um pouco o tamanho das 'beers' e da lata de Coca-Cola e colocar as mesas apenas um pouco mais perto uma da outra, para que o braço possa alcançá-las com mais facilidade? Ou podes diminuir a escala (tamanho) da mesa, pra que ela fique mais baixa. Veja qual a melhor opção. Estando essas pendências resolvidas, pode jogar no repositório e fechar essa *issue*.

**Comment by Kenedw** [comment]
não to conseguindo da push
